fix: handle properly code-toggle and include-code tabs, closes MISC-383
gatling/gatling.io-doc-theme pull request #25
Opened 2022-05-09 13:40 UTC by tpetillot

fix: example site version must be a string, not a float
---

chore: add example in example site to test code toggle and include code shortcodes
---

fix: handle properly code-toggle and include-code tabs, closes MISC-383
---

**Motivation:**
When loading default values, all tabs were reset so only last key was correctly set on default values.

**Modification:**
* data-toggle-key is the key for a common choice
* data-toggle-value is the value for the related choice (when changed, all related data-toggle-key are updated)
* refactor tabs behavior based on those changes

2022-05-12 09:37 UTC, notdryft requested changes

2022-05-12 09:37 UTC, notdryft commented on layouts/shortcodes/code-toggle.html
> +      <button data-toggle-key="build-tool" data-toggle-value="{{ . }}" class="tab-button">
indent

2022-05-12 09:37 UTC, notdryft commented on layouts/shortcodes/include-code.html
> +
remove extra line

2022-05-12 09:37 UTC, notdryft commented on layouts/shortcodes/include-code.html
> +
remove extra line

2022-05-12 09:37 UTC, notdryft commented on exampleSite/content/enterprise/cloud/reference/category-1/part-1/index.md
> +{{</ code-toggle >}}
`{{< /code-toggle >}}` instead of `{{</ code-toggle >}}`.

2022-05-12 09:37 UTC, notdryft commented on assets/js/tabs.ts
> +const DATA_TOGGLE_KEY = "data-toggle-key";
Camel cased `DataToggleKey`?

2022-05-12 09:37 UTC, notdryft commented on assets/js/tabs.ts
> +const DATA_TOGGLE_VALUE = "data-toggle-value";
same

2022-05-12 09:37 UTC, notdryft commented on assets/js/tabs.ts
> +const ACTIVE_CLASS = "active";
same

2022-05-12 12:44 UTC, tpetillot commented on assets/js/tabs.ts
> +const DATA_TOGGLE_KEY = "data-toggle-key";
Javascript constant is all caps IMO

2022-05-12 15:01 UTC, notdryft requested changes

2022-05-13 08:24 UTC, notdryft approved these changes

2022-05-13 08:28 UTC, merged