feat: add include-file short code
gatling/gatling.io-doc-theme pull request #27
Opened 2022-12-21 10:18 UTC by tpetillot

2023-01-10 18:05 UTC, notdryft requested changes

2023-01-10 18:05 UTC, notdryft commented on assets/js/tabs.ts
> +  if (targetKey === "language") {
Removing initializing breaks the first call:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'java')
    at toggleAllTabsOnClick (main.js:1607:42)
    at <stdin> (main.js:1633:9)
    at __require (main.js:5:52)
    at main.js:2663:3
    at main.js:2664:3
```

I think instead of having a boolean storeKey either: the function should be called if the key should be stored, or it scanned internally the default tabs (storable_tabs?) for keys to actually store, and ignores the rest

2023-01-11 08:56 UTC, tpetillot commented on assets/js/tabs.ts
> +  if (targetKey === "language") {
Store key was actually derived from presence of the key in default tabs, i've make it more explicit now.

2023-01-11 09:20 UTC, notdryft approved these changes

2023-01-11 09:21 UTC, merged