feat: shortcode for openapi
gatling/gatling.io-doc-theme pull request #29
Opened 2023-10-21 18:17 UTC by Isammoc

Motivation:
Publish the API documentation

Modifications:
 * openapi shortcode
 * custom scss (to avoid pre background)

Result:
Can use openapi

2023-10-23 07:25 UTC, notdryft requested changes

2023-10-23 07:25 UTC, notdryft commented on layouts/shortcodes/swaggerui.html
> +  });
```suggestion
  window.onload = function () {
    const ui = SwaggerUIBundle({
      url: {{ $original | relURL }},
      dom_id: '#swagger_ui',
      presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIStandalonePreset
      ]
    });
```

2023-10-23 08:12 UTC, tpetillot commented on layouts/partials/footer/script-footer.html
> +<script src="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui-standalone-preset.js" crossorigin="anonymous"></script>
Swagger UI is heavy (https://bundlephobia.com/package/swagger-ui@5.9.0), it shouldn't be downloaded from everywhere in the documentation except pages using the shortcode...

2023-10-23 08:36 UTC, Isammoc commented on layouts/partials/footer/script-footer.html
> +<script src="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui-standalone-preset.js" crossorigin="anonymous"></script>
Yep, I know...
This is a temporary implementation.
I don't want to let an external website access (unpkg.com)

2023-10-23 19:41 UTC, Isammoc commented
Thanks to @notdryft, we found that "`swagger-ui`" npm module does not work, but "`swagger-ui-dist`" does.

So I can make it works and better. only call it once at the end if needed thanks to the `.Page.Store.Set` and `.Page.Store.Get`

2023-10-24 07:10 UTC, notdryft requested changes

2023-10-24 07:10 UTC, notdryft commented on layouts/partials/head/stylesheet.html
> +{{ if .Page.Store.Get "hasOpenApi" -}}
Store is persistent between builds but it is only tied to a single page at a time? Does it work on first build? oO

2023-10-25 08:56 UTC, tpetillot approved these changes
Approved in condition of @notdryft comment

2023-10-25 12:17 UTC, Isammoc commented on layouts/partials/head/stylesheet.html
> +{{ if .Page.Store.Get "hasOpenApi" -}}
Store and Scratch work the same for build.
The difference is only when using hugo as "server"

2023-10-25 12:19 UTC, notdryft approved these changes

2023-10-25 12:27 UTC, merged